export const dataEnemigos=[
    {
        'id':'1',
        'nombre':'Bote de basura',
        'vida':15,
        'ataque':'5',
        'puntos':Math.floor(Math.random() * 10) + 5,
        'velocidad':100,
        'nivel':'1',
        'diseno':'enemie1',
        'width':50,
        'height':50,
        'movimiento':'5',
        'ofzigzag':false
    },
    {
        'id':'2',
        'nombre':'Bolsa de basura',
        'vida':25,
        'ataque':'10',
        'puntos':Math.floor(Math.random() * 10) + 5,
        'velocidad':200,
        'nivel':'1',
        'diseno':'enemie2',
        'width':40,
        'height':40,
        'movimiento':'5',
        'ofzigzag':true
    },
    {
        'id':'3',
        'nombre':'Contaminador aereo',
        'vida':40,
        'ataque':'5',
        'puntos':Math.floor(Math.random() * 15) + 10,
        'velocidad':150,
        'nivel':'1',
        'diseno':'enemie3',
        'width':80,
        'height':80,
        'movimiento':'5',
        'ofzigzag':false
    },
    {
        'id':'4',
        'nombre':'Olvido verde',
        'vida':70,
        'ataque':'15',
        'puntos':Math.floor(Math.random() * 10) + 5,
        'velocidad':100,
        'nivel':'2',
        'diseno':'enemie4',
        'width':60,
        'height':60,
        'movimiento':'5',
        'ofzigzag':false
    },,
    {
        'id':'5',
        'nombre':'Incendiador',
        'vida':80,
        'ataque':'10',
        'puntos':Math.floor(Math.random() * 20) + 10,
        'velocidad':200,
        'nivel':'2',
        'diseno':'enemie5',
        'width':50,
        'height':50,
        'movimiento':'5',
        'ofzigzag':false
    },
    {
        'id':'6',
        'nombre':'Avispa madre',
        'vida':150,
        'ataque':'15',
        'puntos':Math.floor(Math.random() * 20) + 15,
        'velocidad':200,
        'nivel':'2',
        'diseno':'enemie6',
        'width':60,
        'height':60,
        'movimiento':'5',
        'ofzigzag':false
    },
    {
        'id':'7',
        'nombre':'Avispa hijo',
        'vida':50,
        'ataque':'5',
        'puntos':Math.floor(Math.random() * 5) + 3,
        'velocidad':300,
        'nivel':'1',
        'diseno':'enemie7',
        'width':30,
        'height':30,
        'movimiento':'5',
        'ofzigzag':false
    },
    {
        'id':'8',
        'nombre':'Vertedor toxico',
        'vida':350,
        'ataque':'20',
        'puntos':Math.floor(Math.random() * 30) + 15,
        'velocidad':400,
        'nivel':'3',
        'diseno':'enemie8',
        'width':60,
        'height':60,
        'movimiento':'5',
        'ofzigzag':false
    },
    {
        'id':'9',
        'nombre':'Silencio del bosque',
        'vida':400,
        'ataque':'20',
        'puntos':Math.floor(Math.random() * 20) + 10,
        'velocidad':150,
        'nivel':'3',
        'diseno':'enemie9',
        'width':80,
        'height':80,
        'movimiento':'5',
        'ofzigzag':false
    },
    {
        'id':'10',
        'nombre':'Eco Hueco',
        'vida':650,
        'ataque':'20',
        'puntos':Math.floor(Math.random() * 20) + 10,
        'velocidad':50,
        'nivel':'3',
        'diseno':'enemie10',
        'width':90,
        'height':90,
        'movimiento':'5',
        'ofzigzag':false
    }
];